name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STORYBOOK_ACCESSTOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_STORYBOOK_ACCESSTOKEN }}
        run: npx semantic-release
